name: tugasbesar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_svg: ^2.0.16
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/icons/
    - lib/src/assets/images/
    - lib/src/assets/logos/

